spring:
  datasource:
    username: postgres
    password: postgres
    url: jdbc:postgresql://localhost:5432/notes
    driverClassName: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
  redis:
    host: redis #localhost redis
    port: 6379
  session:
    timeout: 60m
    store-type: redis
